<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-8LBRLJ88" name="com.nopcommerce.demo.testsuite.LoginTest" tests="3" failures="1" timestamp="22 Jun 2021 09:37:14 GMT" time="22.369" errors="0">
  <testcase name="verifyUserShouldLoginSuccessfullyWithValidCredentials" time="8.168" classname="com.nopcommerce.demo.testsuite.LoginTest"/>
  <testcase name="verifyUserNavigateToLoginPageSuccessfully" time="4.411" classname="com.nopcommerce.demo.testsuite.LoginTest"/>
  <testcase name="verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials" time="9.790" classname="com.nopcommerce.demo.testsuite.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.nopcommerce.demo.testsuite.LoginTest.verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials(LoginTest.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials -->
</testsuite> <!-- com.nopcommerce.demo.testsuite.LoginTest -->
